server:
  port: 8080

spring:
  application:
    name: external-api-ms

api:
  jsonPlaceholder:
    baseUrl: https://jsonplaceholder.typicode.com

  weatherApi:
    baseUrl: https://api.openweathermap.org/data/2.5
    apiKey: d2198320f9fc7cf8445c50146b1ffe53

  countryApi:
    baseUrl: https://restcountries.com/v3.1

  githubApi:
    baseUrl: https://api.github.com

# RestTemplate timeout config
rest-template:
connect-timeout-ms: 5000
read-timeout-ms: 5000

logging:
  level:
    com.external: INFO


rest:
  client:
    connect-timeout: 5000
    read-timeout: 5000